filler_project_url = 'https://github.com/mattvenn/wokwi_filler'
project_urls = [
	'https://github.com/mattvenn/tinytapeout_m_segments', # already patched
	'https://github.com/gregdavill/tinytapeout_spin0',
	'https://github.com/mole99/wokwi-1bit-alu',
	'https://github.com/ericsmi/tinytapeout_popcnt.git',
	'https://github.com/krasin/wokwi-guess-my-number',
	'https://github.com/johshoff/barrelshifter-wokwi-gds',
	'https://github.com/pretentious7/tinytapeout',
	'https://github.com/GuzTech/wokwi-ripple-carry-adder',
	'https://github.com/kbeckmann/tinytapeout_kbeckmann1',
	'https://github.com/H-S-S-11/tinytapeout-verilog-test',
	'https://github.com/skerr92/tinytapeout_frequency_div',
	'https://github.com/argunda/tinytapeout_dualedgedetector',
	'https://github.com/libokuohai/tinytapeout-2022-08',
	'https://github.com/jglim/tinytapeout_bcd-dec',
	'https://github.com/jglim/tinytapeout_bcd-7seg',
	'https://github.com/tkuester/wokwi-directghost',
	'https://github.com/shahzaibk23/tinytapeout-barrel-shifter',
	'https://github.com/tcptomato/tinytapeout',
	'https://github.com/DaveyPocket/chaser',
	'https://github.com/GuzTech/tinytapeout-4x4-multiplier',
	'https://github.com/derhexenmeister/tinytapeout_nco',
	'https://github.com/mbalestrini/tinytapeout_rgb_lut_test',
	'https://github.com/derhexenmeister/tinytapeout_updwnbcd',
	'https://github.com/bradysalz/pll_tiny_tapeout_demo',
	'https://github.com/pramitpal/tinytapeout_pramit',
	'https://github.com/gregdavill/tinytapeout-verilog-fifo',
	'https://github.com/gregdavill/tinytapeout-wokwi-74x1G00',
	'https://github.com/gregdavill/tinytapeout-wokwi-74x1G02',
	'https://github.com/gregdavill/tinytapeout-wokwi-74xG198',
	'https://github.com/gregdavill/tinytapeout-verilog-7seg-clock',
	'https://github.com/alanvgreen/tinytapeout4bitadder',
	'https://github.com/benlaurie/twistedringcounter',
	'https://github.com/sureshsugumar/tinytapeout_counter',
	'https://github.com/daniestevez/tinytapeout-verilog', 
	'https://github.com/pkuligowski/tinytapeout_tmr',
	'https://github.com/chiplet/tinytapeout-snake',
	'https://github.com/derhexenmeister/tinytapeout_pwm',
	'https://github.com/raha96/tinycharacters-locked',
	'https://github.com/nathancheek/tinytapeout-loop',
	'https://github.com/andars/universal-turing-machine-w5s8', # dup id
	'https://github.com/vmunoz82/tinytapeout_euler1',
	'https://github.com/mikenet213/mikenet213-tt1-verilog',
	'https://github.com/veremenko-y/tinytapeout-ue14500',
	'https://github.com/mikenet213/mikenet213-tt2-verilog',
	'https://github.com/aiunderstand/tinytapeout_asyncbinterconvcomp.git',
	'https://github.com/smunaut/tinytapeout-fifo', # already patched
	'https://github.com/nwtechguy/tinytapeout_BCD_counter',
	'https://github.com/kambadur/bcd_to_7seg',
	'https://github.com/bieganski/tinytapeout_bieganski',
	'https://github.com/TomKeddie/tinytapeout-2022-1',
	'https://github.com/r-a-hoggarth/tinytapeGaloisLFSR',
	'https://github.com/adamgreig/tinytapeout-prn',
	'https://github.com/ianloic/tinytapeout-1',
	'https://github.com/sad-electronics/tinytapeout-clock-divider-asic',
	'https://github.com/gatecat/tinytapeout-lutram-test',
	'https://github.com/tommythorn/tinytapeout-4-bit-cpu',
	'https://github.com/wokwi/tt-game-of-life-cell-popcnt',
	'https://github.com/gatecat/tinytapeout-srlut-test',
	'https://github.com/AdDraw/tinytapeout_demo',
	'https://github.com/cpldcpu/tinydice',
	'https://github.com/cpldcpu/tinytapeout_mcpu6bit',
	'https://github.com/azzeloof/tinytapeout-counter',
	#'https://github.com/georgerennie/tinytapeout-verilog-async-arb', # can't build - replace
    'https://github.com/mattvenn/tinytapeout-341802655228625490', 
	'https://github.com/mwelling/led-blaster',
	'https://github.com/mwelling/figure-8',
	'https://github.com/gatecat/tinytapeout-fpga-test', # already patched
	'https://github.com/cfib/trafficlight-fsm',
	'https://github.com/clj/tinytapeout-verilog-7seg-figure-eight',
	'https://github.com/smunaut/tinytapeout-misc-1', # already patched
	'https://github.com/regymm/tinytapeout-funnyblinky', # fails openlane doesn't fit, has messed with config.tcl
	'https://github.com/Sirawit7205/tinytapeout-2G57-2G58',
	'https://github.com/Sirawit7205/tinytapeout-2G97-2G98',
	'https://github.com/hosein-mokarian/tinytapeout_counter_3to8_decoder',
	'https://github.com/burtyb/srld',
	'https://github.com/Mahnoor-ismail01/tinytapeout-chromatic-3-to-8-Decoder',
	'https://github.com/Shahzaib2028/tinytapeout-4to2Encoder-2to4Decoder',
	'https://github.com/sfmth/tinytapeout-tinycordic',
	'https://github.com/mm21/tinytapeout-led-matrix',
	'https://github.com/jeanthom/tinytapout-lock',
	'https://github.com/AidanMedcalf/tinytapeout-tinyio',
	'https://github.com/ElectricPotato/tinytapeout-hello-world-uart',
	'https://github.com/abdullahkhalids/TinyTapeout-hamming-code',
	'https://github.com/hossein1387/tinytapeout-verilog-test',
	'https://github.com/ChrisPVille/tinytapeout-FROG4bitCPU', # fails patch, easy fix
	'https://github.com/Talha-Ahmed-1/tinytapeout_flop_regfile',
	'https://github.com/skylersaleh/tinytapeout-hello',
	'https://github.com/proppy/tinytapeout-xls-popcount',
	'https://github.com/proppy/tinytapeout-xls-popcount-bithacks', 
	'https://github.com/proppy/tinytapeout-xls-inverter', 
	'https://github.com/mark64/tinytapeout',
	'https://github.com/dave-roo/ddcomparatorandro',
	'https://github.com/splinedrive/tinytapeout-verilog-4x4-multiplier',
	'https://github.com/ThorKn/tinytapeout_shiftregister_8bit',
	'https://github.com/UDXS/tinytapeout-sqrt',
	'https://github.com/coralmw/tinytapeout-css-feedback', 
	'https://github.com/ericsmi/tinytapeout-verilog-div3', # fails openlane hangs forever, works with pdk7 and updated area
	'https://github.com/fluxfocus/jdtt-logic1.git',
	'https://github.com/anm/nyasic',
	'https://github.com/aiunderstand/tinytapeout_bintristateloadablecounter',
	'https://github.com/ThorKn/tinytapeout_shiftregister_challenge',
	'https://github.com/regymm/tinytapeout-mcpi', # openlane fail density error, has messed with config.tcl
	'https://github.com/todd1251/tinytapeout-figure8',
	'https://github.com/CyberGai/tinytapeout-bcd-counter',
	'https://github.com/georgeyhere/tinytapeout-dice-roller',
	'https://github.com/nayanesh-reddy/2-Bit_Add_Mul_Comp',
	'https://github.com/ryancor/half_addr_asic',
	'https://github.com/hovind/tinytapeout-verilog-test',
	'https://github.com/siriusm46/tinytapeout_bcd_decimal',
	'https://github.com/cpldcpu/tinytapeout_mcpu5',
	'https://github.com/goran-mahovlic/tinytapeout-verilog-piano',
	'https://github.com/andars/universal-turing-machine-aw7s8',
	'https://github.com/marcusmueller/hamming74-tapeout',
	'https://github.com/13arn/tinytapeout_counter_steamdeck',
	'https://github.com/johshoff/tinytapeout-verilog',
	'https://github.com/cy384/seven-segment-with-adder',
	'https://github.com/georgerennie/tinytapeout-wokwi-cd4518',
	'https://github.com/ElectricPotato/tinytapeout-picture-printer-b',
	'https://github.com/theFestest/tinytapeout-simple-invert8',
	'https://github.com/ArsenioDev/CustomSiliconTest',
	'https://github.com/mgargano/tinytapeout_alu_with_4bit_7segmetdisplay_decoder',
	'https://github.com/theFestest/tinytapeout-4x4-ram',
	'https://github.com/michael-christen/wokwi-verilog-asic-experiment',
	'https://github.com/craigcc-frii/tinytapeout_craig',
	'https://github.com/youngpines/r2rdac_tinytapeout_demo',
	'https://github.com/toybuilder/learn-tinytapeout',
	'https://github.com/eggsactly/tinytapeout_demo',
	'https://github.com/gsegura96/tinytapeout-chisel', 
	'https://github.com/abf149/fbna_like_verilog_abf149',
	'https://github.com/MC-SecPat/tinytapeout_chi2shares',
	'https://github.com/MC-SecPat/tinytapeout_chi3shares',
	'https://github.com/Adil8442/tiny_tapeout_test',
	#'https://github.com/MC-SecPat/tinytapeout_chiDOM', # remove, - empty project
    'https://github.com/mattvenn/tinytapeout-341802448429515346',  # filler
	'https://github.com/r4d10n/tinytapeout-HELLo-3orLd-7seg',
	'https://github.com/proppy/tinytapeout-xls-graydec',
	'https://github.com/prabaldutta/tinytapeout_adi',
	'https://github.com/maehw/wokwi-verilog-gds-wolf-goat-cabbage',
	'https://github.com/ThorKn/tinytapeout_pattern_player',
	'https://github.com/rigobertoruiz98/cts_fsm',
	'https://github.com/rajarshiroy/tinytapout0_rajarshi',
	'https://github.com/BarsMonster/MicroASIC',
	'https://github.com/kammoh/tinytapeout-chisel',
	'https://github.com/cpldcpu/TinyTapeout_TrainLED',
	'https://github.com/malkam03/tinytapeout-game-of-life',
	'https://github.com/BarsMonster/MicroAsicV',
	'https://github.com/maehw/wokwi-verilog-gds-lowspeed-tiny-uart',
	'https://github.com/smunaut/tinytapeout-smolram', # already patched
	'https://github.com/sirejdua/6bit-cellular-automata-tinytapeout',
	'https://github.com/DuaneSand/TinyTapeout-Hello',
	'https://github.com/tzachari/tinytapeout-lab11',
	'https://github.com/mattvenn/tinytapeout-marc',
    'https://github.com/mattvenn/tinytapeout-laura', # already patched
    ]
